# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import kagglehub
warnings.filterwarnings('ignore')

# Load Dataset

In [2]:
# Download latest version
path = kagglehub.dataset_download("mdmahfuzsumon/global-gold-price-dataset-18332026-monthly")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/mdmahfuzsumon/global-gold-price-dataset-18332026-monthly/1.archive...

100%|██████████| 7.89k/7.89k [00:00<00:00, 13.4MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/mdmahfuzsumon/global-gold-price-dataset-18332026-monthly/versions/1

In [10]:
df_path = path + "/monthly.csv"
df = pd.read_csv(df_path)
df.head()

      Date  Price
0  1833-01  18.93
1  1833-02  18.93
2  1833-03  18.93
3  1833-04  18.93
4  1833-05  18.93

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2318 non-null   object
 1   Price   2318 non-null   float64
dtypes: float64(1), object(1)
memory usage: 36.3+ KB

In [12]:
df.describe()

             Price
count  2318.000000
mean    232.232352
std     508.694544
min      17.060000
25%      18.940000
50%      20.680000
75%     176.300000
max    5019.970000

# Predicting Gold Price